version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-cms}
      POSTGRES_PASSWORD: ${DB_PASS:-secret}
      POSTGRES_DB: ${DB_NAME:-cmsdb}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-minioadmin}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  imagor:
    image: shumc/imagor:latest
    environment:
      IMAGOR_SECRET: "devsecret"
      IMAGOR_STORAGE_PATH: "fs://data"
    ports:
      - "8000:8000"
    volumes:
      - imagor_data:/data

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      - db
      - redis
      - minio
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: cms
      DB_PASS: secret
      DB_NAME: cmsdb
      DB_SSLMODE: disable

      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: media
      MINIO_USE_SSL: false

      APP_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  db_data:
  minio_data:
  imagor_data:
